version: '3.9'

services:
  auth:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: auth
    restart: unless-stopped
    ports:
      - 8082:8082
    expose:
      - '8082'
